apiVersion: v1
kind: Service
metadata:
  name: {{ include "blacklist.fullname" . }}
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
  selector:
    {{- include "blacklist.selectorLabels" . | nindent 4 }}
