# To create a service account
# oc create sa <service_account_name> 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <service_account_name>
  namespace: <current_project>


# View secrets of a service account
#oc describe sa <service_account_name>

# Add priviledge "view" to service account:
# oc policy add-role-to-user view system:serviceaccount:<project>:<service_account_name>

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: top-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: robot
  namespace: hitlist

# You can also grant access to a specific service account in a project.
# For example, from the project to which the service account belongs,xi
# use the -z flag and specify the <service_account_name>

# oc policy add-role-to-user <role_name> -z <service_account_name>
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <rolebinding_name>
  namespace: <current_project_name>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <role_name>
subjects:
- kind: ServiceAccount
  name: <service_account_name>
  namespace: <current_project_name>
