apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-blacklist
  namespace: hitlist
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8native/
    repoURL: https://github.com/gary-crowe/hitlist
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
