apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blacklist-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: theblacklist
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-hitlist/base
    repoURL: git@github.com:gary-crowe/argoCD.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
#   syncOptions:
#   - CreateNamespace=true
