{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort:  {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  wildcardPolicy: None
{{- end }}
