apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeType: openshift-storage.cephfs.csi.ceph.com
  storageClassName: gc
  claimRef:
    name: mysql
    namespace: thelist
