---
# Simple play to set machines up
- name: Initialse servers
  hosts: all
  tasks:

  - name: Register server
    shell:
      cmd: subscription-manager register --username "{{ RHID }}" --password "{{ RHPWD }}"

  - name: Subscribe
    shell:
      cmd: subscription-manager attach --pool=8a85f99a71efe841017212ebcef0765c

  - name: Disable repos
    shell:
      cmd: subscription-manager repos --disable="*"

  - name: Set Repos
    shell:
      cmd: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ose-3.11-rpms --enable=rhel-7-server-ansible-2.9-rpms

  - name: Install packages
    package:
      name:
        - yum
        - wget
        - git
        - net-tools
        - bind-utils
        - yum-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
      state: latest

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Initialse servers
    hosts: all
    tasks:

  - name: Reboot the machine
    reboot:

  - name: Install packages
    package:
      name:
        - openshift-ansible
        - docker-1.13.1
        - atomic
      state: latest

  - name: Copy over docker config file
    copy:
      content: |
        DEVS=/dev/vdb
        VG=docker-vg
      dest: /etc/sysconfig/docker-storage-setup
      backup: yes

  - name: Initialise docker storage
    shell:
      cmd: docker-storage-setup

  - name: Start Docker service 
    service:
     name: docker
     state: started
     enabled: true
