apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /export/reg
    server: nfs4.ocp4.local
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    name: mysql
#    namespace: reggy
