apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /export/vol1
    server: nfs4.ocp4.local
  persistentVolumeReclaimPolicy: Retain
