apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-test
  namespace: hitlist
spec:
  ingressClassName: flask-hitlist-test
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: srv-flask
            port:
              number: 8080

