namespace: blacklist
commonLabels:
  application: theblacklist
commonAnnotations:
  CreatedBy: gary.crowe@computacenter.com
resources:
  - pvc.yml
  - secret.yml
  - mysql-deply.yml
  - svc-mysql.yml
  - flask.yml
  - svc-flask.yml
