apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: theblacklist
commonLabels:
  application: thehitlist
commonAnnotations:
  CreatedBy: gary.crowe@computacenter.com
resources:
  - namespace.yml
  - pvc.yml
  - configmap.yml
  - secret.yml
  - mysql-deply.yml
  - svc-mysql.yml
  - flask.yml
  - svc-flask.yml
  - route.yml
