---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: database
    app.kubernetes.io/name: mysql-database
    app.kubernetes.io/part-of: thehitlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: db-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets
              key: db_root_password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          value: offenders
        - name: MYSQL_USER
          value : gary

        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
