apiVersion: v1
kind: Service
metadata:
  name: srv-flask
  namespace: hitlist
spec:
  selector:
    app: blacklist
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
