apiVersion: kustomize.config.k8s.io/v1beta
kind: Kustomization
namespace: hitlist
commonLabels:
  application: blacklist
commonAnnotations:
  CreatedBy: gary.crowe@computacenter.com
resources:
  - pvc.yml
  - configmap.yml
  - secret.yml
  - mysql-deply.yml
  - svc-mysql.yml
  - flask.yml
  - svc-flask.yml
  - gateway.yml
  - virtual-service.yml
