apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blacklist-vs
spec:
  hosts:
  - "*"
  gateways:
  - blacklist-gateway
  http:
  - route:
    - destination:
        host: svc-flask
        port:
          number: 5000
